#include<iostream>
using namespace std;
int main()
{
	cout << "------------------------------------------------------------------------------------------------------------------------";
	cout << "\t \t \t A C++ program to print your name and your university roll." << endl;
	string name = "Muhammad Ahmed Subhani" , rollNo = "SU92-BSSEM-S25-018" ;
	cout << name << "\n" << rollNo << endl ;
	cout << "------------------------------------------------------------------------------------------------------------------------";
	cout << "\t \t \t A C++ Program to perform Arithmetic operations on 2 numbers taken by user." << endl;
	int a,b,c;
	cout << " Enter first number: ";
    cin >> a;
    cout << " \n Enter second number: ";
    cin >> b;
    c = a+b ;
    cout << " ADDITION: " << c << endl ;
    c = a-b ;
    cout << " SUBTRACT: "<< c << endl ;
    c = a*b ;
    cout << " MULTIPLY: "<< c << endl ;
    c = a/b ;
    cout << " DIVISION: " << c << endl ;
    c = a%b ;
    cout << " MODULUS: "<< c << endl ;
    cout << "------------------------------------------------------------------------------------------------------------------------";
	cout << "\t \t \t A C++ program to print the area of the rectangle. (Take input from user)." << endl;
	float length, width, area;
	cout << " \n Enter the Length of the rectangle; ";
	cin >> length ;
    cout << " \n Enter the Width of the rectangle; ";
	cin >> width ;
	area = length * width ;
	cout << " \n Area of the rectangle will be: " << area << endl ;
	cout << "------------------------------------------------------------------------------------------------------------------------";
	cout << "\t \t \t A program that will show the following outputs simply by using cout statements." << endl;
	cout << " (a) (b) (c) (d) " << endl;
	cout << "------------------------------------------------------------------------------------------------------------------------";
	cout << "\t \t \t A C++ program illustrates the use of sizeof() function which is used to find the memory space allocated for each C++ data type." << endl;
    cout << "Size of int: " << sizeof(int) << endl;
    cout << "Size of unsigned int: " << sizeof(unsigned int)<< endl;
    cout << "Size of char: " << sizeof(char) << endl;
    cout << "Size of float: " << sizeof(float) << endl;
    cout << "Size of double: " << sizeof(double) << endl;
    cout << "Size of bool: " << sizeof(bool) << endl;
    cout << "Size of long long: " << sizeof(long long) << endl;
    cout << "------------------------------------------------------------------------------------------------------------------------";
	cout << "\t \t \t A C++ program to swap two numbers by using 3rd variables." << endl;
	int d = 5 ,e = 6,f ;
	cout << " Before Swap " << "\n a:" << d << "\n b:" << e;
	f = d;
	d = e;
	e = f;
	cout << " \n After Swap " << "\n a:" << d << "\n b:" << e << endl;
	cout << "------------------------------------------------------------------------------------------------------------------------";
	cout << "\t \t \t A C++ program to swap two numbers without using 3rd variables." << endl;
	int g = 5 ,h = 6;
	cout << " Before Swap " << "\n a:" << g << "\n b:" << h;
	g = g+h;
	h = g-h;
	g = g-h;
	cout << " \n After Swap " << "\n a:" << g << "\n b:" << h << endl;
	cout << "------------------------------------------------------------------------------------------------------------------------";
	cout << "\t \t \t A program converts a temperature from Celsius to Fahrenheit. Use the following formula: F = 1.8 x C +" << endl;
	float celsius, fahrenheit;
    cout << "Enter temperature in Celsius:  ";
    cin >> celsius;
    fahrenheit = 1.8 * celsius + 32;
    cout << " \n Temperature in Fahrenheit: " << fahrenheit << endl; 
	return 0;
 }